# -*- coding: utf-8 -*-
"""Assignment 1 — Use AI Segmentation in CAMUS DATASET, Final Version.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I3c_6hwLtzU7btG8rPf95y-KxuF0xybl
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install SimpleITK

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import SimpleITK as sitk
import os
import h5py
import os
from tqdm import tqdm
import random # Import the random module
import nibabel as nib # Import nibabel
import matplotlib.pyplot as plt # Import matplotlib

# %matplotlib inline

fig_size = plt.rcParams["figure.figsize"]

fig_size[0] = 7
fig_size[1] = 9
plt.rcParams["figure.figsize"] = fig_size

data_path = "/content/drive/MyDrive/ch_database"

import SimpleITK as sitk

def nii_to_array(path):
    """
    Read a *.nii.gz file stored in path and return it as a numpy array.
    """
    return sitk.GetArrayFromImage(sitk.ReadImage(path, sitk.sitkFloat32))

view = random.choice(['2CH', '4CH'])

image_dir = os.path.join(data_path, view, "images")
mask_dir = os.path.join(data_path, view, "masks")

# Get the list of image files here
image_files = [f for f in os.listdir(image_dir) if f.endswith('.nii.gz')]
chosen_file = random.choice(image_files)  # Now image_files is defined

# Construct the mask file path based on the chosen image file
mask_file = chosen_file.replace('.nii.gz', '_gt.nii.gz')

image_path = os.path.join(image_dir, chosen_file)
mask_path = os.path.join(mask_dir, mask_file)



import random # Import the random module
import nibabel as nib # Import nibabel
import matplotlib.pyplot as plt # Import matplotlib
import numpy as np # Import numpy


def visualisation(data_path, random_slice=True):
    # Load image and mask data using nibabel
    image_data = nii_to_array(image_path) # Use nii_to_array with SimpleITK
    mask_data = nii_to_array(mask_path)  # Use nii_to_array with SimpleITK

    # Handle 2D and 3D images, selecting a slice if necessary
    if image_data.ndim == 3:
        num_slices = image_data.shape[2]
        slice_idx = random.randint(0, num_slices - 1) if random_slice else num_slices // 2
        image_slice = image_data[:, :, slice_idx]
        mask_slice = mask_data[:, :, slice_idx]
        slice_info = f"Slice {slice_idx}"
    elif image_data.ndim == 2:
        image_slice = image_data
        mask_slice = mask_data
        slice_info = ""
    else:
        print(f"Error: Unexpected image dimensions for {chosen_file}")
        return

    # Create and display the plot
    fig, axs = plt.subplots(1, 2, figsize=(12, 6))

    axs[0].imshow(image_slice, cmap='gray')
    axs[0].set_title(f'Image - {chosen_file}\n{slice_info} ({view})')
    axs[0].axis('off')

    axs[1].imshow(mask_slice)
    axs[1].set_title(f'Mask - {mask_file}\n{slice_info} ({view})')
    axs[1].axis('off')

    plt.tight_layout()
    plt.show()

    # Return image_data and mask_data so they can be accessed outside the function
    return image_data, mask_data

# Visualize a random image and mask (either from 4CH or 2CH)
image_data, mask_data = visualisation(data_path, random_slice=True) # Assign the returned values to image_data and mask_data


# Now you can use image_data and mask_data outside the function
print(np.shape(image_data)) # Print the shape of image_data
print(np.shape(mask_data)) # Print the shape of mask_data

import skimage.transform
import SimpleITK as sitk
import cv2
import numpy as np

def preprocess(path, is_mask=False, target_size=(320, 320)):
    """
    Pré-processa imagem ou máscara para treinamento com PyTorch.
    - Lê com SimpleITK
    - Redimensiona
    - Normaliza se for imagem
    - Retorna tensor com shape [1, H, W] para imagem e [H, W] para máscara
    """
    import SimpleITK as sitk
    import numpy as np
    import cv2
    import skimage.transform

    # Lê a imagem com SimpleITK
    data = sitk.GetArrayFromImage(sitk.ReadImage(path, sitk.sitkFloat32))

    # Usa o primeiro slice se for 3D
    if data.ndim == 3:
        data = data[0]

    # Redimensionamento
    if is_mask:
        # Resize com nearest-neighbor (mantém valores inteiros)
        data_resized = skimage.transform.resize(
            data, target_size, order=0, preserve_range=True, anti_aliasing=False
        ).astype(np.uint8)  # convertendo para inteiro (valores de classe)
        return torch.from_numpy(data_resized).long()  # shape: [H, W]
    else:
        # Resize com interpolação bicúbica
        data_resized = cv2.resize(data, target_size, interpolation=cv2.INTER_CUBIC)
        data_resized = data_resized / 255.0  # Normaliza imagem
        data_tensor = np.expand_dims(data_resized, axis=0)  # shape: [1, H, W]
        return torch.from_numpy(data_tensor).float()

def visualise_multiple(image_paths, mask_paths, views, num_images=6, random_slice=True):
    """
    Visualizes multiple image-mask pairs in a single figure.

    Args:
        image_paths: A list of tuples, where each tuple is (image_path, view).
        mask_paths: A list of corresponding mask paths.
        views: A list of view types (e.g., '2CH', '4CH'). (Not directly used, but kept for context)
        num_images: The number of image-mask pairs to visualize.
        random_slice: Whether to select a random slice from 3D images.
    """
    # Ensure we don't request more images than available
    num_images_to_display = min(num_images, len(image_paths))

    # Calculate the number of rows and columns for the subplot grid
    # We'll have 2 columns (image and mask) and num_images_to_display rows
    n_cols = 2
    n_rows = num_images_to_display

    # Create the figure and subplots
    # Adjust figsize to accommodate multiple rows
    fig, axs = plt.subplots(n_rows, n_cols, figsize=(12, n_rows * 6))

    # Flatten the axs array if there's only one row
    if n_rows == 1:
        axs = np.expand_dims(axs, axis=0)


    # Get random indices to select images
    # Create a list of indices from the available paths
    indices = random.sample(range(len(image_paths)), num_images_to_display)


    for i, idx in enumerate(indices):
        image_path, view = image_paths[idx]
        mask_path = mask_paths[idx]

        # Load data
        image_data = nii_to_array(image_path)
        mask_data = nii_to_array(mask_path)

        # Handle 2D/3D images and select slice
        if image_data.ndim == 3:
            num_slices = image_data.shape[2]
            slice_idx = random.randint(0, num_slices - 1) if random_slice else num_slices // 2
            image_slice = image_data[:, :, slice_idx]
            mask_slice = mask_data[:, :, slice_idx]
            slice_info = f"Slice {slice_idx}"
        elif image_data.ndim == 2:
            image_slice = image_data
            mask_slice = mask_data
            slice_info = ""
        else:
            print(f"Error: Unexpected image dimensions for {os.path.basename(image_path)}")
            # Hide the axes for this row if there's an error
            axs[i, 0].set_visible(False)
            axs[i, 1].set_visible(False)
            continue # Skip to the next iteration

        # Display image
        axs[i, 0].imshow(image_slice, cmap='gray')
        axs[i, 0].set_title(f'Image - {os.path.basename(image_path)}\n{slice_info} ({view})')
        axs[i, 0].axis('off')

        # Display mask
        axs[i, 1].imshow(mask_slice)
        axs[i, 1].set_title(f'Mask - {os.path.basename(mask_path)}\n{slice_info} ({view})')
        axs[i, 1].axis('off')

    plt.tight_layout()
    plt.show()

# Collect all image and mask paths from both 2CH and 4CH views
all_image_paths = []
all_mask_paths = []

views = ['2CH', '4CH']
for view in views:
    image_dir = os.path.join(data_path, view, "images")
    mask_dir = os.path.join(data_path, view, "masks")

    # Get the list of image files
    image_files = [f for f in os.listdir(image_dir) if f.endswith('.nii.gz')]

    # Pair images with their corresponding masks
    for chosen_file in image_files:
        mask_file = chosen_file.replace('.nii.gz', '_gt.nii.gz')
        image_path = os.path.join(image_dir, chosen_file)
        mask_path = os.path.join(mask_dir, mask_file)

        if os.path.exists(mask_path): # Ensure a mask exists for the image
            all_image_paths.append((image_path, view)) # Store path and view
            all_mask_paths.append(mask_path)

# Ensure the number of image paths and mask paths match
if len(all_image_paths) != len(all_mask_paths):
    print("Warning: Mismatch between the number of image and mask files found.")

# Call the visualise_multiple function to display the selected examples
visualise_multiple(all_image_paths, all_mask_paths, views, num_images=6, random_slice=True)

import skimage.transform
import SimpleITK as sitk
import cv2
import numpy as np
import torch # Import the torch module
from torch.utils.data import Dataset # Import the Dataset class
from glob import glob # Import the glob module


class CHDataset(Dataset):
    def __init__(self, image_paths, mask_paths):
        self.image_paths = image_paths
        self.mask_paths = mask_paths

    def get_image_mask_pairs(self, data_path):
        views = ['2CH', '4CH']
        image_paths = [] # Change image_path to image_paths
        mask_paths = [] # Change mask_path to mask_paths

        for view in views:
            image_dir = os.path.join(data_path, view, 'images')
            mask_dir = os.path.join(data_path, view, 'masks')

            image_files = sorted(glob(os.path.join(image_dir, '*.nii.gz')))
            for img_path in image_files:
                filename = os.path.basename(img_path)
                mask_path = os.path.join(mask_dir, filename.replace('.nii.gz', '_gt.nii.gz'))
                if os.path.exists(mask_path):
                    image_paths.append(img_path) # Append to image_paths
                    mask_paths.append(mask_path) # Append to mask_paths
                else:
                    print(f"[AVISO] Máscara não encontrada para {filename}")

        return image_paths, mask_paths # Return image_paths and mask_paths

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        image_tensor = preprocess(self.image_paths[idx], is_mask=False)  # torch.Size([1, H, W])
        mask_tensor = preprocess(self.mask_paths[idx], is_mask=True)     # torch.Size([H, W])


        unique_vals = torch.unique(mask_tensor)
        return image_tensor, mask_tensor

# Call get_image_mask_pairs to define image_paths and mask_paths before creating the dataset
image_paths, mask_paths = CHDataset(image_paths=[], mask_paths=[]).get_image_mask_pairs(data_path)
# Create an instance of the dataset
dataset = CHDataset(image_paths, mask_paths)  # Pass both image_paths and mask_paths


# Choose a random index for visualization
index = random.randint(0, len(dataset) - 1)

# Get the preprocessed image and mask
img, mask = dataset[index] # Assign the output to img and mask

# Print the shape of img and mask
print(img.shape)
print(mask.shape)

# Obtenha a imagem e máscara pré-processadas
image, mask = dataset[index]
# Visualize a imagem e máscara com a dimensão do canal
plt.figure(figsize=(10, 5))

# Exibindo a imagem e máscara com a dimensão extra do canal (não usamos squeeze)
plt.subplot(1, 2, 1)
plt.imshow(image[0, :, :], cmap='gray')  # Acessando a imagem sem remover o canal
plt.title('Imagem Pré-processada')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(mask[ :, :])  # Acessando a máscara sem remover o canal
plt.title('Máscara Pré-processada')
plt.axis('off')

plt.show()
print(img.shape)  # Esperado: torch.Size([1, 300, 300])
print(mask.shape) # Esperado: torch.Size([1, 300, 300])

import matplotlib.pyplot as plt
import random
import SimpleITK as sitk


# Crie uma instância do dataset
index = random.randint(0, len(dataset) - 1)

image_preprocessed, mask_preprocessed = dataset[index]

# Obtenha o caminho da imagem original
# Change dataset.image_path to dataset.image_paths
image_path = dataset.image_paths[index]

# Leia a imagem original usando SimpleITK
image_original = sitk.GetArrayFromImage(sitk.ReadImage(image_path, sitk.sitkFloat32))

# Se a imagem original for 3D, pegue o primeiro slice
if image_original.ndim == 3:
    image_original = image_original[0, :, :]

# Visualize a imagem original, a imagem pré-processada e a máscara
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(image_original, cmap='gray')
plt.title('Original Image ')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(image_preprocessed.squeeze(), cmap='gray')
plt.title('Pre-processed Image')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(mask_preprocessed.squeeze())
plt.title('Pre-processed Mask')
plt.axis('off')

plt.show()

!pip install segmentation-models-pytorch

from torch.utils.data import Subset, DataLoader
import segmentation_models_pytorch as smp # import the library as smp
import keras
import torch.optim as optim
from segmentation_models_pytorch.losses import DiceLoss, JaccardLoss
# Import IoU and Fscore from the correct location
from segmentation_models_pytorch.utils.metrics import IoU, Fscore
import torch.nn as nn  # Importe nn para CrossEntropyLoss
import torch
from tqdm import tqdm
import time
from sklearn.model_selection import train_test_split

model = smp.Unet(
    encoder_name="resnet34",        # Escolha do encoder
    encoder_weights="imagenet",     # Pré-treinamento com ImageNet
    in_channels=1,                 # Número de canais de entrada (1 para imagens em escala de cinza)
    classes=4,                   # Número de classes de saída (incluindo o fundo)
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

from sklearn.model_selection import train_test_split

# Access the lists of image and mask paths from the dataset
image_paths = dataset.image_paths
mask_paths = dataset.mask_paths

# Now use train_test_split with these lists
image_paths_train, image_paths_rem, mask_paths_train, mask_paths_rem = train_test_split(
    image_paths, mask_paths, train_size=0.8, random_state=42
)

# Split the remaining data into validation and test sets
image_paths_val, image_paths_test, mask_paths_val, mask_paths_test = train_test_split(
    image_paths_rem, mask_paths_rem, test_size=0.5, random_state=42
)

# Print the sizes of the datasets
print(f"Training set size: {len(image_paths_train)}")
print(f"Validation set size: {len(image_paths_val)}")
print(f"Testing set size: {len(image_paths_test)}")

# Create datasets
train_dataset = CHDataset(
    image_paths=image_paths_train,
    mask_paths=mask_paths_train,
)

val_dataset = CHDataset(
    image_paths=image_paths_val,  # Pass image_paths here
    mask_paths=mask_paths_val,
)

test_dataset = CHDataset(
    image_paths=image_paths_test,  # Pass image_paths here
    mask_paths=mask_paths_test,
)

# Create DataLoaders
train_loader = torch.utils.data.DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True,
    num_workers=4,
    pin_memory=True
)


val_loader = torch.utils.data.DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=4,
    pin_memory=True,
    prefetch_factor=2
)

test_loader = torch.utils.data.DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=4,
    pin_memory=True,
    prefetch_factor=2
)

import torch

if torch.cuda.is_available():
    print("GPU is available")
else:
    print("GPU is not available")

import torch
import numpy as np
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

# Função para calcular o IoU
def calculate_iou(preds, targets, num_classes):
    iou_per_class = []
    preds = preds.view(-1)
    targets = targets.view(-1)

    for cls in range(num_classes):
        pred_inds = preds == cls
        target_inds = targets == cls

        intersection = (pred_inds & target_inds).sum().item()
        union = (pred_inds | target_inds).sum().item()

        if union == 0:
            iou = np.nan  # Se não houver pixel da classe
        else:
            iou = intersection / union
        iou_per_class.append(iou)

    return iou_per_class

# Função para calcular o Dice
def calculate_dice(preds, targets, num_classes):
    dice_per_class = []
    preds = preds.view(-1)
    targets = targets.view(-1)

    for cls in range(num_classes):
        pred_inds = preds == cls
        target_inds = targets == cls

        intersection = (pred_inds & target_inds).sum().item()
        dice = (2. * intersection) / (pred_inds.sum().item() + target_inds.sum().item() + 1e-8)

        dice_per_class.append(dice)

    return dice_per_class

# Função para calcular a acurácia por classe
def calculate_accuracy_per_class(preds, targets, num_classes):
    accuracy_per_class = []
    preds = preds.view(-1)
    targets = targets.view(-1)

    for cls in range(num_classes):
        pred_inds = preds == cls
        target_inds = targets == cls

        correct = (pred_inds & target_inds).sum().item()
        total = target_inds.sum().item()

        if total == 0:
            accuracy = np.nan
        else:
            accuracy = correct / total

        accuracy_per_class.append(accuracy)

    return accuracy_per_class

# Função para calcular a matriz de confusão
def calculate_confusion_matrix(preds, targets, num_classes):
    preds = preds.view(-1).cpu().numpy()  # Garantir que esteja na CPU para compatibilidade
    targets = targets.view(-1).cpu().numpy()  # Garantir que esteja na CPU para compatibilidade

    cm = confusion_matrix(targets, preds, labels=list(range(num_classes)))
    return cm

# Função para calcular precisão, recall e F1
def calculate_precision_recall_f1(preds, targets, num_classes):
    preds = preds.view(-1).cpu().numpy()  # Garantir que esteja na CPU para compatibilidade
    targets = targets.view(-1).cpu().numpy()  # Garantir que esteja na CPU para compatibilidade

    precision = precision_score(targets, preds, labels=list(range(num_classes)), average=None, zero_division=0)
    recall = recall_score(targets, preds, labels=list(range(num_classes)), average=None, zero_division=0)
    f1 = f1_score(targets, preds, labels=list(range(num_classes)), average=None, zero_division=0)

    return precision, recall, f1

# Função para calcular a média macro
def macro_average(values_per_class):
    valid_values = [v for v in values_per_class if not np.isnan(v)]  # Ignora NaNs
    if not valid_values:
        return np.nan
    return np.mean(valid_values)

def bce_jaccard_loss(y_pred, y_true):
    bce_loss = F.binary_cross_entropy_with_logits(y_pred, y_true)

    smooth = 1e-6
    intersection = (y_pred * y_true).sum(dim=[1, 2, 3])
    union = (y_pred + y_true).sum(dim=[1, 2, 3])

    jaccard_loss = 1 - (intersection + smooth) / (union - intersection + smooth)

    return bce_loss + jaccard_loss.mean()



import os
import time
import torch
import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm

def train_model(model, train_loader, val_loader, optimizer, criterion, num_classes, num_epochs=20, checkpoint_dir="/content/drive/MyDrive", patience=5):
    os.makedirs(checkpoint_dir, exist_ok=True)
    model = model.to(device)  # Move o modelo para o dispositivo especificado

    best_val_loss = float('inf')
    epochs_without_improvement = 0

    history = {
        'train_loss': [], 'val_loss': [],
        'train_iou': [], 'val_iou': [],
        'train_dice': [], 'val_dice': [],
        'train_acc': [], 'val_acc': []
    }

    for epoch in range(1, num_epochs + 1):
        print(f"\n🚀 Epoch {epoch}/{num_epochs}")
        epoch_start = time.time()

        # TRAIN
        train_loss, train_preds, train_targets = train_one_epoch(
            model, train_loader, optimizer, criterion, num_classes, device  # Passa o device aqui
        )

        # VALIDATE
        # Remove device from the function call arguments here
        val_loss, val_preds, val_targets = validate_one_epoch(
            model, val_loader, criterion, num_classes
        )

        # Metrics
        train_iou = calculate_iou(train_preds, train_targets, num_classes)
        train_dice = calculate_dice(train_preds, train_targets, num_classes)
        train_accuracy = calculate_accuracy_per_class(train_preds, train_targets, num_classes)

        val_iou = calculate_iou(val_preds, val_targets, num_classes)
        val_dice = calculate_dice(val_preds, val_targets, num_classes)
        val_accuracy = calculate_accuracy_per_class(val_preds, val_targets, num_classes)

        # Store
        history['train_loss'].append(train_loss)
        history['val_loss'].append(val_loss)
        history['train_iou'].append(macro_average(train_iou))
        history['val_iou'].append(macro_average(val_iou))
        history['train_dice'].append(macro_average(train_dice))
        history['val_dice'].append(macro_average(val_dice))
        history['train_acc'].append(macro_average(train_accuracy))
        history['val_acc'].append(macro_average(val_accuracy))

        # Log
        print(f"\n📊 Metrics for Epoch {epoch}")
        print(f"Train Loss: {train_loss:.4f} | Validation Loss: {val_loss:.4f}")
        print(f"Train IoU: {macro_average(train_iou):.4f} | Val IoU: {macro_average(val_iou):.4f}")
        print(f"Train Dice: {macro_average(train_dice):.4f} | Val Dice: {macro_average(val_dice):.4f}")
        print(f"Train Accuracy: {macro_average(train_accuracy):.4f} | Val Accuracy: {macro_average(val_accuracy):.4f}")

        # Checkpoints
        if epoch % 5 == 0:
            checkpoint_path = os.path.join(checkpoint_dir, f"model_epoch_{epoch}.pth")
            torch.save(model.state_dict(), checkpoint_path)
            print(f"💾 Saved checkpoint at {checkpoint_path}")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            epochs_without_improvement = 0
            best_model_path = os.path.join(checkpoint_dir, "best_model.pth")
            torch.save(model.state_dict(), best_model_path)
            print("🏆 New best model saved!")
        else:
            epochs_without_improvement += 1
            print(f"😴 No improvement for {epochs_without_improvement} epochs")
            if epochs_without_improvement >= patience:
                print("\n⛔ Early stopping triggered!")
                break

        print(f"🕒 Epoch time: {time.time() - epoch_start:.2f}s")

    # Final model save
    final_model_path = os.path.join(checkpoint_dir, "final_model.pth")
    torch.save(model.state_dict(), final_model_path)
    print(f"\n💾 Final model saved at {final_model_path}")
    print("✅ Training Finished.")
    return history

def train_one_epoch(model, data_loader, optimizer, criterion, num_classes, device): # Add device as a parameter
    model.train()
    running_loss = 0.0
    all_preds = []
    all_targets = []

    for images, masks in tqdm(data_loader, desc="Training", leave=False):
        # Move data to the specified device
        images = images.to(device)
        masks = masks.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, masks)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        preds = torch.argmax(outputs, dim=1)

        all_preds.append(preds.cpu())
        all_targets.append(masks.cpu())

    all_preds = torch.cat(all_preds)
    all_targets = torch.cat(all_targets)
    return running_loss / len(data_loader), all_preds, all_targets


def validate_one_epoch(model, data_loader, criterion, num_classes): # Remove device as a parameter
    model.eval()
    running_loss = 0.0
    all_preds = []
    all_targets = []

    with torch.no_grad():
        for images, masks in tqdm(data_loader, desc="Validation", leave=False):
            # Move data to the specified device
            images = images.to(device) # device is a global variable
            masks = masks.to(device) # device is a global variable
            outputs = model(images)
            loss = criterion(outputs, masks)
            running_loss += loss.item()

            preds = torch.argmax(outputs, dim=1)
            all_preds.append(preds.cpu())
            all_targets.append(masks.cpu())

    all_preds = torch.cat(all_preds)
    all_targets = torch.cat(all_targets)
    return running_loss / len(data_loader), all_preds, all_targets

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)
num_classes = 4  # Definindo o número de classes para a segmentação
num_epochs = 20
checkpoint_dir = '/content/drive/MyDrive'
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

train_model(model, train_loader, val_loader, optimizer, criterion, num_classes, num_epochs, checkpoint_dir=checkpoint_dir, patience=5)

import matplotlib.pyplot as plt
import numpy as np

# Your provided data:
train_dice = [np.float64(0.7295714120197576),
  np.float64(0.9123558255960464),
  np.float64(0.9290919710874416),
  np.float64(0.9352388269294638),
  np.float64(0.9424992866564836),
  np.float64(0.9481671056913749),
  np.float64(0.9518927011916081),
  np.float64(0.9537049540187055),
  np.float64(0.9569735826505625),
  np.float64(0.9595285205509784),
  np.float64(0.9620414789993547),
  np.float64(0.9662693522516423),
  np.float64(0.9660505080862443),
  np.float64(0.9672300083226453),
  np.float64(0.9682585688842161),
  np.float64(0.9712289391101332),
  np.float64(0.9708053715937615),
  np.float64(0.9718872872424471),
  np.float64(0.971984370477591),
  np.float64(0.9737621283594653)]
val_dice = [np.float64(0.8879044651480092),
  np.float64(0.9169462265143976),
  np.float64(0.916849847479116),
  np.float64(0.9265632002069806),
  np.float64(0.9346399213988879),
  np.float64(0.9361319797965423),
  np.float64(0.9280229110502206),
  np.float64(0.9385110495286662),
  np.float64(0.9371798461112272),
  np.float64(0.9441942536537715),
  np.float64(0.9418997694104394),
  np.float64(0.9435443308324541),
  np.float64(0.9464471351150165),
  np.float64(0.9445637185377838),
  np.float64(0.9501228824593374),
  np.float64(0.9493050998295107),
  np.float64(0.9500824960564893),
  np.float64(0.9518835600541367),
  np.float64(0.951541783488047),
  np.float64(0.9537166934479181)]

# Create the plot
epochs = range(1, len(train_dice) + 1)
plt.plot(epochs, train_dice, label='Train Dice', marker='o')
plt.plot(epochs, val_dice, label='Validation Dice', marker='o')
plt.title('Dice per Epoch')
plt.xlabel('Epoch')
plt.ylabel('Dice')
plt.legend()
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Your provided data:
train_iou = [np.float64(0.5874308408261829),
  np.float64(0.8425509424290476),
  np.float64(0.8701592063187423),
  np.float64(0.8805755621876288),
  np.float64(0.8930857236517515),
  np.float64(0.9029719897136622),
  np.float64(0.9095212622404351),
  np.float64(0.9127699450056339),
  np.float64(0.9185374353939364),
  np.float64(0.9231785880240193),
  np.float64(0.9276978032962389),
  np.float64(0.9354087362811182),
  np.float64(0.9350163895416121),
  np.float64(0.9371803040899547),
  np.float64(0.9390681626960976),
  np.float64(0.9445595489388663),
  np.float64(0.9437774962792935),
  np.float64(0.9457926546022457),
  np.float64(0.9459700577737186),
  np.float64(0.9492867809752427)]
val_iou = [np.float64(0.8039185149167807),
  np.float64(0.8499766924348295),
  np.float64(0.8498489150606551),
  np.float64(0.8659757210738104),
  np.float64(0.8795830547219204),
  np.float64(0.8822027582335727),
  np.float64(0.8684050138801367),
  np.float64(0.8862726589374398),
  np.float64(0.8839082604865871),
  np.float64(0.8959524625801893),
  np.float64(0.8919632125477948),
  np.float64(0.8949179215036424),
  np.float64(0.899883581086713),
  np.float64(0.896600879653452),
  np.float64(0.9063300467601503),
  np.float64(0.9049759284014052),
  np.float64(0.9063290177066914),
  np.float64(0.909515828669104),
  np.float64(0.9088187884895405),
  np.float64(0.9127664862186147)]


# Create the plot
epochs = range(1, len(train_iou) + 1)  # Assuming you have data for 20 epochs
plt.plot(epochs, train_iou, label='Train IoU', marker='o')
plt.plot(epochs, val_iou, label='Validation IoU', marker='o')
plt.title('IoU per Epoch')
plt.xlabel('Epoch')
plt.ylabel('IoU')
plt.legend()
plt.grid(True)  # Add a grid for better readability
plt.show()

import matplotlib.pyplot as plt

# Your training history data
history = {
    'train_loss': [0.6613, 0.2990, 0.1976, 0.1494, 0.1190, 0.0986, 0.0853, 0.0768, 0.0679, 0.0622, 0.0566, 0.0497, 0.0482, 0.0457, 0.0431, 0.0390, 0.0389, 0.0370, 0.0362, 0.0339],
    'val_loss': [0.4030, 0.2399, 0.1874, 0.1441, 0.1201, 0.1084, 0.1114, 0.0948, 0.0914, 0.0820, 0.0826, 0.0818, 0.0770, 0.0782, 0.0716, 0.0728, 0.0728, 0.0702, 0.0701, 0.0702]
}

# Epochs
epochs = range(1, len(history['train_loss']) + 1)

# Plot the training and validation losses
plt.plot(epochs, history['train_loss'], label='Training Loss')
plt.plot(epochs, history['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()



import matplotlib.pyplot as plt
import numpy as np

# Your training history data
history = {
    'train_acc': [np.float64(0.7938391322588036),
                  np.float64(0.920467474796014),
                  np.float64(0.9334970625887707),
                  np.float64(0.9377186998105462),
                  np.float64(0.9441628904409648),
                  np.float64(0.9486673976942835),
                  np.float64(0.9523495222389984),
                  np.float64(0.9540384110184358),
                  np.float64(0.9565764040107388),
                  np.float64(0.9596465809252251),
                  np.float64(0.961840224546958),
                  np.float64(0.9661548807619886),
                  np.float64(0.9658877780707746),
                  np.float64(0.9667196349347804),
                  np.float64(0.9681385793895433),
                  np.float64(0.971241267632605),
                  np.float64(0.9706665005703713),
                  np.float64(0.971873069702613),
                  np.float64(0.9719083284096826),
                  np.float64(0.9736371270120983)],
    'val_acc': [np.float64(0.9083367217603561),
                np.float64(0.9194563887515278),
                np.float64(0.9138600035124763),
                np.float64(0.9265587516715237),
                np.float64(0.929780203122903),
                np.float64(0.9423112105221787),
                np.float64(0.9384688686127695),
                np.float64(0.9307337304343368),
                np.float64(0.9300191133553526),
                np.float64(0.9379614351076171),
                np.float64(0.9345531387199906),
                np.float64(0.9309283774337992),
                np.float64(0.9532509255406489),
                np.float64(0.9471906613302981),
                np.float64(0.9534320227507158),
                np.float64(0.951803438997194),
                np.float64(0.9512503265709932),
                np.float64(0.9526912340151359),
                np.float64(0.9565644963960598),
                np.float64(0.9564983693157647)]
}

# Epochs
epochs = range(1, len(history['train_acc']) + 1)

# Plot the training and validation accuracies
plt.plot(epochs, history['train_acc'], label='Training Accuracy')
plt.plot(epochs, history['val_acc'], label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

import matplotlib.pyplot as plt

# Define the losses
train_loss = 0.0339
val_loss = 0.0702
test_loss = 0.0777

# Create the bar graph
losses = [train_loss, val_loss, test_loss]
labels = ['Train', 'Validation', 'Test']

plt.bar(labels, losses, color=['blue', 'orange', 'green'])
plt.title('Loss Comparison')
plt.ylabel('Loss')
plt.show()

# Defina o caminho no Google Drive para salvar o modelo
model_save_path = "/content/drive/MyDrive/final_model.pth"

import torch
import time
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

def test_model(model, test_loader, criterion, num_classes, model_load_path="/content/drive/MyDrive/final_model.pth", model_save_path="/content/drive/MyDrive/tested_model.pth"):
    print("\n📂 Loading saved model for testing...")

    # Load model
    model.load_state_dict(torch.load(model_load_path))  # No need to specify map_location for CPU
    model.eval()
    print(f"✅ Model loaded from: {model_load_path}")

    start_time = time.time()
    running_loss = 0.0
    all_preds = []
    all_targets = []

    with torch.no_grad():
        for images, masks in tqdm(test_loader, desc="🔍 Testing"):
            # No device shifting, everything remains on the CPU
            outputs = model(images)  # Forward pass
            loss = criterion(outputs, masks)  # Calculate loss
            running_loss += loss.item()  # Accumulate loss

            preds = torch.argmax(outputs, dim=1)  # Get predictions (max along the class dimension)

            all_preds.append(preds)  # Keep predictions on CPU
            all_targets.append(masks)  # Keep targets on CPU

    # Concatenate all predictions and targets across batches
    all_preds = torch.cat(all_preds, dim=0)
    all_targets = torch.cat(all_targets, dim=0)

    # Metrics Calculation (IoU, Dice, Accuracy, etc.)
    iou = calculate_iou(all_preds, all_targets, num_classes)
    dice = calculate_dice(all_preds, all_targets, num_classes)
    accuracy = calculate_accuracy_per_class(all_preds, all_targets, num_classes)
    precision, recall, f1 = calculate_precision_recall_f1(all_preds, all_targets, num_classes)
    cm = calculate_confusion_matrix(all_preds, all_targets, num_classes)

    # Save the tested model to the specified path
    torch.save(model.state_dict(), model_save_path)  # Save the model after testing
    print(f"\n💾 Tested model saved to: {model_save_path}")

    # Print and plot results
    results = {
        "test_loss": running_loss / len(test_loader),
        "iou": macro_average(iou),
        "dice": macro_average(dice),
        "accuracy": macro_average(accuracy),
        "precision": np.mean(precision),
        "recall": np.mean(recall),
        "f1_score": np.mean(f1)
    }

    # 📊 Display the test metrics
    print(f"\n📊 Test Metrics:")
    print(f"Test Loss: {results['test_loss']:.4f}")
    print(f"IoU (macro avg): {results['iou']:.4f}")
    print(f"Dice (macro avg): {results['dice']:.4f}")
    print(f"Accuracy (macro avg): {results['accuracy']:.4f}")
    print(f"Precision: {results['precision']:.4f}")
    print(f"Recall: {results['recall']:.4f}")
    print(f"F1 Score: {results['f1_score']:.4f}")

    # 📌 Confusion Matrix visualization
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=[f'Pred {i}' for i in range(num_classes)],
                yticklabels=[f'True {i}' for i in range(num_classes)])
    plt.title("Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("Ground Truth")
    plt.tight_layout()
    plt.show()

    elapsed_time = time.time() - start_time
    print(f"\n🕒 Total Test Time: {elapsed_time:.2f} seconds")

    return results



import matplotlib.pyplot as plt

# Epochs
epochs = [1, 2, 3, 4, 5, 6]

# Training Metrics
train_iou = [0.6269, 0.8480, 0.8730, 0.8914, 0.8999, 0.9086]
train_dice = [0.7540, 0.9156, 0.9307, 0.9416, 0.9464, 0.9514]
train_accuracy = [0.8473, 0.9322, 0.9382, 0.9432, 0.9464, 0.9509]

# Validation Metrics
val_iou = [0.8310, 0.8547, 0.8678, 0.8651, 0.8848, 0.8851]
val_dice = [0.9050, 0.9199, 0.9278, 0.9260, 0.9377, 0.9379]
val_accuracy = [0.9269, 0.9387, 0.9279, 0.9272, 0.9263, 0.9258]

# Create plots for each metric
plt.figure(figsize=(12, 4))

# Plot IoU
plt.subplot(1, 3, 1)
plt.plot(epochs, train_iou, label='Train IoU', marker='o')
plt.plot(epochs, val_iou, label='Validation IoU', marker='o')
plt.title('IoU per Epoch')
plt.xlabel('Epoch')
plt.ylabel('IoU')
plt.legend()

# Plot Dice
plt.subplot(1, 3, 2)
plt.plot(epochs, train_dice, label='Train Dice', marker='o')
plt.plot(epochs, val_dice, label='Validation Dice', marker='o')
plt.title('Dice per Epoch')
plt.xlabel('Epoch')
plt.ylabel('Dice')
plt.legend()

# Plot Accuracy
plt.subplot(1, 3, 3)
plt.plot(epochs, train_accuracy, label='Train Accuracy', marker='o')
plt.plot(epochs, val_accuracy, label='Validation Accuracy', marker='o')
plt.title('Accuracy per Epoch')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

import torch
import matplotlib.pyplot as plt
from tqdm import tqdm

def evaluate_model(model, test_loader, criterion):
    model.eval()  # Set the model to evaluation mode (turns off dropout, batch normalization, etc.)
    running_loss = 0.0

    with torch.no_grad():  # Disables gradient computation, saving memory and computation
        for images, masks in tqdm(test_loader, desc="Evaluating"):
            # No device handling; assume the data is already on the CPU
            outputs = model(images)
            loss = criterion(outputs, masks)
            running_loss += loss.item()

    return running_loss / len(test_loader)  # Average loss across all batches

final_model.load_state_dict(torch.load("/content/drive/MyDrive/final_model.pth"))
tested_model.load_state_dict(torch.load("/content/drive/MyDrive/tested_model.pth"))

# Evaluate both models
final_model_loss = evaluate_model(final_model, test_loader, criterion)
tested_model_loss = evaluate_model(tested_model, test_loader, criterion)

# Create the plot
models = ['Final Model', 'Tested Model']
losses = [final_model_loss, tested_model_loss]

plt.bar(models, losses, color=['blue', 'green'])
plt.title('Test Loss Comparison')
plt.ylabel('Test Loss')
plt.show()

import matplotlib.pyplot as plt
import random
import torch

def visualize_predictions(model, dataset, num_images=5):
    """
    Visualizes predictions of a segmentation model on the CPU.

    Args:
        model: The trained segmentation model.
        dataset: The dataset to use for visualization.
        num_images: The number of images to visualize.
    """

    model.eval()  # Set model to evaluation mode
    # We ensure the model is on the CPU by calling .cpu()
    model.cpu()

    # Get random indices from the dataset
    indices = random.sample(range(len(dataset)), num_images)

    for idx in indices:
        image, mask = dataset[idx]  # Get image and mask

        # Make sure the image is on the CPU
        image = image.cpu()

        with torch.no_grad():
            output = model(image.unsqueeze(0))  # Add batch dimension and make prediction
            prediction = torch.argmax(output, dim=1).squeeze()  # Get prediction and remove batch dimension

        # Plot original image, ground truth mask, and predicted mask
        plt.figure(figsize=(15, 5))

        plt.subplot(1, 3, 1)
        plt.imshow(image.squeeze(), cmap='gray')  # Remove channel dimension for display
        plt.title('Original Image')
        plt.axis('off')

        plt.subplot(1, 3, 2)
        plt.imshow(mask)  # Ground truth mask
        plt.title('Ground Truth Mask')
        plt.axis('off')

        plt.subplot(1, 3, 3)
        plt.imshow(prediction)  # Predicted mask
        plt.title('Predicted Mask')
        plt.axis('off')

        plt.show()

# Load your trained model
model_path = "/content/drive/MyDrive/final_model.pth"  # Or wherever you saved your model
# Explicitly load the model onto the CPU
model.load_state_dict(torch.load(model_path, map_location=torch.device('cpu')))

# Visualize predictions
visualize_predictions(model, test_dataset, num_images=5)

import matplotlib.pyplot as plt
import random
import torch
import numpy as np

def visualize_predictions(model, dataset, num_images=5, class_names=None):
    """
    Visualizes predictions of a segmentation model on the CPU, highlighting classes.

    Args:
        model: The trained segmentation model.
        dataset: The dataset to use for visualization.
        num_images: The number of images to visualize.
        class_names: A list of class names corresponding to the class indices.
                      If None, class indices will be used as labels.
    """

    model.eval()  # Set model to evaluation mode
    model.cpu()  # Ensure the model is on the CPU

    # Get random indices from the dataset
    indices = random.sample(range(len(dataset)), num_images)

    for idx in indices:
        image, mask = dataset[idx]  # Get image and mask
        image = image.cpu()  # Make sure the image is on the CPU

        with torch.no_grad():
            output = model(image.unsqueeze(0))  # Add batch dimension and make prediction
            prediction = torch.argmax(output, dim=1).squeeze()  # Get prediction and remove batch dimension

        # Plot original image, ground truth mask, and predicted mask
        plt.figure(figsize=(15, 5))

        plt.subplot(1, 3, 1)
        plt.imshow(image.squeeze(), cmap='gray')  # Remove channel dimension for display
        plt.title('Original Image')
        plt.axis('off')

        plt.subplot(1, 3, 2)
        plt.imshow(mask, cmap='viridis')  # Ground truth mask with 'viridis' colormap
        plt.title('Ground Truth Mask')
        plt.axis('off')

        plt.subplot(1, 3, 3)
        # Create a custom colormap with distinct colors for each class
        num_classes = len(np.unique(prediction.cpu().numpy())) #get the number of classes from the prediction
        colors = plt.cm.get_cmap('viridis', num_classes) #create the custom colormap
        # Display the prediction with the custom colormap
        im = plt.imshow(prediction, cmap=colors)
        plt.title('Predicted Mask')
        plt.axis('off')

        # Add a colorbar if class names are provided
        if class_names is not None:
          #get the unique class values and create a colorbar for them
          unique_classes = np.unique(prediction.cpu().numpy())
          cbar = plt.colorbar(im, ticks=unique_classes)
          #if class names were provided, use them as labels for the colorbar
          if class_names is not None:
            cbar.ax.set_yticklabels(class_names)  # Set class names as labels

        plt.show()

# ... (other parts of your code) ...

class_names = ['Background', 'Class 1', 'Class 2', 'Class 3']  # Example class names

# Visualize predictions with class names
visualize_predictions(model, test_dataset, num_images=5, class_names=class_names)

import matplotlib.pyplot as plt
import random
import torch
import numpy as np

def visualize_predictions(model, dataset, num_images=5, class_names=None, remove_class=None):
    """
    Visualizes predictions of a segmentation model on the CPU, highlighting classes
    and optionally removing a specified class.

    Args:
        model: The trained segmentation model.
        dataset: The dataset to use for visualization.
        num_images: The number of images to visualize.
        class_names: A list of class names corresponding to the class indices.
                      If None, class indices will be used as labels.
        remove_class: The class index (integer) to remove from the visualization.
                       If None, no class is removed.
    """

    model.eval()  # Set model to evaluation mode
    model.cpu()  # Ensure the model is on the CPU

    # Get random indices from the dataset
    indices = random.sample(range(len(dataset)), num_images)

    for idx in indices:
        image, mask = dataset[idx]  # Get image and mask
        image = image.cpu()  # Make sure the image is on the CPU

        with torch.no_grad():
            output = model(image.unsqueeze(0))  # Add batch dimension and make prediction
            prediction = torch.argmax(output, dim=1).squeeze()  # Get prediction and remove batch dimension

        # Remove specified class if provided
        if remove_class is not None:
            mask[mask == remove_class] = 0  # Set pixels of the class to 0 in ground truth
            prediction[prediction == remove_class] = 0  # Set pixels of the class to 0 in prediction

        # Plot original image, ground truth mask, and predicted mask
        plt.figure(figsize=(15, 5))

        plt.subplot(1, 3, 1)
        plt.imshow(image.squeeze(), cmap='gray')  # Remove channel dimension for display
        plt.title('Original Image')
        plt.axis('off')

        plt.subplot(1, 3, 2)
        plt.imshow(mask, cmap='viridis')  # Ground truth mask with 'viridis' colormap
        plt.title('Ground Truth Mask')
        plt.axis('off')

        plt.subplot(1, 3, 3)
        # Create a custom colormap with distinct colors for each class
        num_classes = len(np.unique(prediction.cpu().numpy()))
        colors = plt.cm.get_cmap('viridis', num_classes)
        # Display the prediction with the custom colormap
        im = plt.imshow(prediction, cmap=colors)
        plt.title('Predicted Mask')
        plt.axis('off')

        # Add a colorbar if class names are provided
        if class_names is not None:
            unique_classes = np.unique(prediction.cpu().numpy())
            cbar = plt.colorbar(im, ticks=unique_classes)
            if class_names is not None:
                cbar.ax.set_yticklabels(class_names)  # Set class names as labels

        plt.show()

import matplotlib.pyplot as plt
import random
import torch
import numpy as np

def visualize_predictions(model, dataset, num_images=5, class_names=None, remove_class=None, alpha=0.5):
    """
    Visualizes predictions of a segmentation model on the CPU, highlighting classes,
    optionally removing a specified class, and overlaying the mask on the image.

    Args:
        model: The trained segmentation model.
        dataset: The dataset to use for visualization.
        num_images: The number of images to visualize.
        class_names: A list of class names corresponding to the class indices.
                      If None, class indices will be used as labels.
        remove_class: The class index (integer) to remove from the visualization.
                       If None, no class is removed.
        alpha: Transparency level of the mask overlay (0.0 - transparent, 1.0 - opaque).
    """
    model.eval()  # Set model to evaluation mode
    model.cpu()  # Ensure the model is on the CPU

    # Get random indices from the dataset
    indices = random.sample(range(len(dataset)), num_images)

    for idx in indices:
        image, mask = dataset[idx]  # Get image and mask
        image = image.cpu()  # Make sure the image is on the CPU

        with torch.no_grad():
            output = model(image.unsqueeze(0))  # Add batch dimension and make prediction
            prediction = torch.argmax(output, dim=1).squeeze()  # Get prediction and remove batch dimension

        # Remove specified class if provided
        if remove_class is not None:
            mask[mask == remove_class] = 0  # Set pixels of the class to 0 in ground truth
            prediction[prediction == remove_class] = 0  # Set pixels of the class to 0 in prediction

        # Plot original image, ground truth mask, and predicted mask
        plt.figure(figsize=(15, 5))

        plt.subplot(1, 3, 1)
        plt.imshow(image.squeeze(), cmap='gray')  # Remove channel dimension for display
        plt.title('Original Image')
        plt.axis('off')

        plt.subplot(1, 3, 2)
        plt.imshow(image.squeeze(), cmap='gray')  # Display the image
        # Overlay the mask with transparency and adjust colormap
        plt.imshow(mask, cmap='jet', alpha=alpha)
        plt.title('Ground Truth Mask Overlay')
        plt.axis('off')

        plt.subplot(1, 3, 3)
        plt.imshow(image.squeeze(), cmap='gray')  # Display the image
        # Create a custom colormap with distinct colors for each class
        num_classes = len(np.unique(prediction.cpu().numpy()))
        colors = plt.cm.get_cmap('jet', num_classes)  # Change colormap to 'jet'
        # Display the prediction with the custom colormap and overlay it with transparency
        im = plt.imshow(prediction, cmap=colors, alpha=alpha)
        plt.title('Predicted Mask Overlay')
        plt.axis('off')

        # Add a colorbar with all class labels if class names are provided
        if class_names is not None:
            unique_classes = np.unique(prediction.cpu().numpy())
            # Ensure all classes are represented in the colorbar
            all_classes = np.arange(len(class_names))
            cbar = plt.colorbar(im, ticks=all_classes)
            cbar.ax.set_yticklabels(class_names)  # Set class names as labels

        plt.show()

class_names = ['Background', 'Class 1', 'Class 2', 'Class 3']
# If you want to remove a class, set remove_class_index to the desired class index
# For example, to remove 'Class 2', set remove_class_index = 2
remove_class_index = None  # or set to an index (0, 1, 2, 3) to remove a class

# Visualize predictions with overlay and class removal
visualize_predictions(
    model,
    test_dataset,
    num_images=5,
    class_names=class_names,
    remove_class=remove_class_index,
    alpha=0.3  # Adjust transparency here
)

import matplotlib.pyplot as plt
import random
import torch
import numpy as np
from skimage.measure import find_contours

def visualize_predictions(model, dataset, num_images=5, class_names=None, alpha=0.5):
    """
    Visualizes predictions of a segmentation model on the CPU,
    highlighting only the borders of Class 1, 2, and 3.

    Args:
        model: The trained segmentation model.
        dataset: The dataset to use for visualization.
        num_images: The number of images to visualize.
        class_names: A list of class names corresponding to the class indices.
                      If None, class indices will be used as labels.
        alpha: Transparency level of the mask overlay (0.0 - transparent, 1.0 - opaque).
    """
    model.eval()  # Set model to evaluation mode
    model.cpu()  # Ensure the model is on the CPU

    # Get random indices from the dataset
    indices = random.sample(range(len(dataset)), num_images)

    for idx in indices:
        image, mask = dataset[idx]  # Get image and mask
        image = image.cpu()  # Make sure the image is on the CPU

        with torch.no_grad():
            output = model(image.unsqueeze(0))  # Add batch dimension and make prediction
            prediction = torch.argmax(output, dim=1).squeeze()  # Get prediction and remove batch dimension

        # Plot original image with contours of Class 1, 2, and 3
        plt.figure(figsize=(10, 5))

        plt.subplot(1, 2, 1)
        plt.imshow(image.squeeze(), cmap='gray')  # Original image
        plt.title('Original Image')
        plt.axis('off')

        plt.subplot(1, 2, 2)
        plt.imshow(image.squeeze(), cmap='gray')  # Original image

        # Find and plot contours for each class (1, 2, 3)
        for class_index in range(1, len(class_names)):
            contours = find_contours(prediction.cpu().numpy() == class_index, 0.5)
            for contour in contours:
                plt.plot(contour[:, 1], contour[:, 0], linewidth=2,
                         label=class_names[class_index] if contour == contours[0] else "")

        plt.title('Predicted Mask Borders (Class 1, 2, 3)')
        plt.axis('off')
        plt.legend() # Show legend for class labels

        plt.show()

!pip install opencv-python matplotlib

import matplotlib.pyplot as plt
import numpy as np

def visualize_predictions_with_contours(image, ground_truth_mask, predicted_mask, class_names=None):
    """
    Visualiza uma imagem com duas máscaras sobrepostas como contornos.

    Args:
        image: A imagem original em tons de cinza.
        ground_truth_mask: A máscara original (ground truth).
        predicted_mask: A máscara predita.
        class_names: Uma lista opcional de nomes de classes.
    """

    # Define as cores para as máscaras
    ground_truth_colors = [(255, 0, 0), (0, 255, 0), (0, 0, 128)]  # Vermelho, Verde, Azul Escuro
    predicted_colors = [(255, 0, 255), (255, 255, 0), (0, 128, 255)]  # Magenta, Amarelo, Azul Claro

    # Exibe a imagem original em tons de cinza
    plt.imshow(image, cmap='gray')

    # Adiciona os contornos da máscara original (ground truth)
    for class_index in range(len(ground_truth_colors)):
        contours, _ = cv2.findContours(
            (ground_truth_mask == class_index + 1).astype(np.uint8),
            cv2.RETR_EXTERNAL,
            cv2.CHAIN_APPROX_SIMPLE
        )
        plt.drawContours(
            contours,
            -1,
            ground_truth_colors[class_index],
            2,  # Espessura da linha
            lineType=cv2.LINE_8  # Linha sólida
        )

    # Adiciona os contornos da máscara predita (tracejados)
    for class_index in range(len(predicted_colors)):
        contours, _ = cv2.findContours(
            (predicted_mask == class_index + 1).astype(np.uint8),
            cv2.RETR_EXTERNAL,
            cv2.CHAIN_APPROX_SIMPLE
        )
        plt.drawContours(
            contours,
            -1,
            predicted_colors[class_index],
            2,  # Espessura da linha
            lineType=cv2.LINE_4  # Linha tracejada
        )

    # Adiciona nomes de classes, se fornecidos
    if class_names is not None:
        plt.legend(class_names)

    plt.title('Imagem com Máscaras Sobrepostas')
    plt.axis('off')
    plt.show()

import matplotlib.pyplot as plt
import numpy as np

def visualize_predictions_with_contours(image, ground_truth_mask, predicted_mask, class_names=None):
    """
    Visualizes predictions with contours for ground truth and predicted masks.

    Args:
        image: The original ultrasound image (NumPy array).
        ground_truth_mask: The ground truth mask (NumPy array).
        predicted_mask: The predicted mask (NumPy array).
        class_names: A list of class names (optional).
    """

    # Define colors for contours
    gt_colors = ['red', 'green', 'darkblue']  # Ground truth colors
    pred_colors = ['magenta', 'yellow', 'lightblue']  # Predicted colors

    # Create figure and axes
    fig, ax = plt.subplots(figsize=(10, 5))

    # Display the original image in grayscale
    ax.imshow(image, cmap='gray')

    # Overlay ground truth contours
    for i in range(1, len(gt_colors) + 1):  # Assuming classes start from 1
        contour = ax.contour(ground_truth_mask == i, levels=[0.5], colors=[gt_colors[i - 1]], linestyles='solid')
        if class_names is not None:
            contour.collections[0].set_label(class_names[i - 1] + ' (Ground Truth)')  # Add label for legend

    # Overlay predicted contours with dashed lines
    for i in range(1, len(pred_colors) + 1):  # Assuming classes start from 1
        contour = ax.contour(predicted_mask == i, levels=[0.5], colors=[pred_colors[i - 1]], linestyles='dashed')
        if class_names is not None:
            contour.collections[0].set_label(class_names[i - 1] + ' (Predicted)')  # Add label for legend

    # Customize plot
    ax.set_title('Ultrasound Image with Overlaid Masks')
    ax.axis('off')  # Turn off axes
    if class_names is not None:
        ax.legend()  # Display legend if class names are provided

    plt.show()

visualize_predictions_with_contours(image, ground_truth_mask, predicted_mask, class_names=['Class 1', 'Class 2', 'Class 3'])

import matplotlib.pyplot as plt
import numpy as np
import torch  # Import torch for tensor operations

def visualize_predictions_with_contours(image, ground_truth_mask, predicted_mask, class_names=None):
    """
    Visualizes predictions with contours for ground truth and predicted masks.

    Args:
        image: The original ultrasound image (NumPy array or torch.Tensor).
        ground_truth_mask: The ground truth mask (NumPy array or torch.Tensor).
        predicted_mask: The predicted mask (NumPy array or torch.Tensor).
        class_names: A list of class names (optional).
    """

    # Convert tensors to NumPy arrays if needed
    if isinstance(image, torch.Tensor):
        image = image.cpu().numpy()
    if isinstance(ground_truth_mask, torch.Tensor):
        ground_truth_mask = ground_truth_mask.cpu().numpy()
    if isinstance(predicted_mask, torch.Tensor):
        predicted_mask = predicted_mask.cpu().numpy()

    # Define colors for contours
    gt_colors = ['red', 'green', 'darkblue']  # Ground truth colors
    pred_colors = ['magenta', 'yellow', 'lightblue']  # Predicted colors

    # Create figure and axes
    fig, ax = plt.subplots(figsize=(10, 5))

    # Display the original image in grayscale
    ax.imshow(image.squeeze(), cmap='gray')  # Squeeze to remove channel dimension if necessary

    # Overlay ground truth contours
    for i in range(1, len(gt_colors) + 1):  # Assuming classes start from 1
        contour = ax.contour(ground_truth_mask == i, levels=[0.5], colors=[gt_colors[i - 1]], linestyles='solid')
        if class_names is not None:
            contour.collections[0].set_label(class_names[i - 1] + ' (Ground Truth)')  # Add label for legend

    # Overlay predicted contours with dashed lines
    for i in range(1, len(pred_colors) + 1):  # Assuming classes start from 1
        contour = ax.contour(predicted_mask == i, levels=[0.5], colors=[pred_colors[i - 1]], linestyles='dashed')
        if class_names is not None:
            contour.collections[0].set_label(class_names[i - 1] + ' (Predicted)')  # Add label for legend

    # Customize plot
    ax.set_title('Ultrasound Image with Overlaid Masks')
    ax.axis('off')  # Turn off axes
    if class_names is not None:
        ax.legend()  # Display legend if class names are provided

    plt.show()

import matplotlib.pyplot as plt
import random
import torch
import numpy as np

# ... (rest of your functions) ...

# Get an image and mask from your dataset
image, mask = test_dataset[random.randint(0, len(test_dataset) - 1)]

# Get the model's prediction
with torch.no_grad(): #disable gradient calculation for inference
    output = model(image.unsqueeze(0).cpu()) #add batch dimension and move to CPU if necessary
    prediction = torch.argmax(output, dim=1).squeeze().cpu() #get the predicted class and move to CPU

# Now call the visualization function
visualize_predictions_with_contours(image.cpu().numpy(), mask.cpu().numpy(), prediction.cpu().numpy(), class_names=['Class 1', 'Class 2', 'Class 3'])

import matplotlib.pyplot as plt
import random
import torch
import numpy as np

def visualize_predictions_as_contours(model, dataset, num_images=5, class_names=None):
    """
    Visualizes predictions of a segmentation model on the CPU, highlighting classes
    and optionally removing a specified class.

    Args:
        model: The trained segmentation model.
        dataset: The dataset to use for visualization.
        num_images: The number of images to visualize.
        class_names: A list of class names corresponding to the class indices.
                      If None, class indices will be used as labels.
    """

    model.eval()  # Set model to evaluation mode
    model.cpu()  # Ensure the model is on the CPU

    # Get random indices from the dataset
    indices = random.sample(range(len(dataset)), num_images)

    for idx in indices:
        image, mask = dataset[idx]  # Get image and mask
        image = image.cpu()  # Make sure the image is on the CPU

        with torch.no_grad():
            output = model(image.unsqueeze(0))  # Add batch dimension and make prediction
            prediction = torch.argmax(output, dim=1).squeeze()  # Get prediction and remove batch dimension

        # Plot original image, ground truth mask, and predicted mask
        plt.figure(figsize=(15, 5))

        plt.subplot(1, 3, 1)
        plt.imshow(image.squeeze(), cmap='gray')  # Remove channel dimension for display
        plt.title('Original Image')
        plt.axis('off')

        # Ground truth mask as contours
        plt.subplot(1, 3, 2)
        plt.imshow(image.squeeze(), cmap='gray')  # Background image
        # Create colormap for ground truth contours
        gt_colors = ['r', 'g', 'darkblue']
        for i, color in enumerate(gt_colors):
            contours = measure.find_contours(mask.cpu().numpy(), i + 0.5)  # Adjust level for each class
            for contour in contours:
                plt.plot(contour[:, 1], contour[:, 0], color, linewidth=2)
        plt.title('Ground Truth Mask (Contours)')
        plt.axis('off')

        # Predicted mask as contours
        plt.subplot(1, 3, 3)
        plt.imshow(image.squeeze(), cmap='gray')  # Background image
        # Create colormap for predicted contours
        pred_colors = ['magenta', 'yellow', 'lightblue']
        for i, color in enumerate(pred_colors):
            contours = measure.find_contours(prediction.cpu().numpy(), i + 0.5)  # Adjust level for each class
            for contour in contours:
                plt.plot(contour[:, 1], contour[:, 0], color + '--', linewidth=2)  # Dashed lines for predicted
        plt.title('Predicted Mask (Contours)')
        plt.axis('off')

        plt.show()

import matplotlib.pyplot as plt
import random
import torch
import numpy as np
from skimage import measure  # Import the 'measure' module from skimage

def visualize_predictions_as_contours(model, dataset, num_images=5, class_names=None):
    """
    Visualizes predictions of a segmentation model on the CPU, highlighting classes
    and optionally removing a specified class.

    Args:
        model: The trained segmentation model.
        dataset: The dataset to use for visualization.
        num_images: The number of images to visualize.
        class_names: A list of class names corresponding to the class indices.
                      If None, class indices will be used as labels.
    """

    model.eval()  # Set model to evaluation mode
    model.cpu()  # Ensure the model is on the CPU

    # Get random indices from the dataset
    indices = random.sample(range(len(dataset)), num_images)

    for idx in indices:
        image, mask = dataset[idx]  # Get image and mask
        image = image.cpu()  # Make sure the image is on the CPU

        with torch.no_grad():
            output = model(image.unsqueeze(0))  # Add batch dimension and make prediction
            prediction = torch.argmax(output, dim=1).squeeze()  # Get prediction and remove batch dimension

        # Plot original image, ground truth mask, and predicted mask
        plt.figure(figsize=(15, 5))

        plt.subplot(1, 3, 1)
        plt.imshow(image.squeeze(), cmap='gray')  # Remove channel dimension for display
        plt.title('Original Image')
        plt.axis('off')

        # Ground truth mask as contours
        plt.subplot(1, 3, 2)
        plt.imshow(image.squeeze(), cmap='gray')  # Background image
        # Create colormap for ground truth contours
        gt_colors = ['r', 'g', 'darkblue']
        for i, color in enumerate(gt_colors):
            contours = measure.find_contours(mask.cpu().numpy(), i + 0.5)  # Adjust level for each class
            for contour in contours:
                plt.plot(contour[:, 1], contour[:, 0], color, linewidth=2)
        plt.title('Ground Truth Mask (Contours)')
        plt.axis('off')

        # Predicted mask as contours
        plt.subplot(1, 3, 3)
        plt.imshow(image.squeeze(), cmap='gray')  # Background image
        # Create colormap for predicted contours
        pred_colors = ['magenta', 'yellow', 'lightblue']
        for i, color in enumerate(pred_colors):
            contours = measure.find_contours(prediction.cpu().numpy(), i + 0.5)  # Adjust level for each class
            for contour in contours:
                plt.plot(contour[:, 1], contour[:, 0], color + '--', linewidth=2)  # Dashed lines for predicted
        plt.title('Predicted Mask (Contours)')
        plt.axis('off')

        plt.show()

import matplotlib.pyplot as plt
import random
import torch
import numpy as np
from skimage import measure  # Import the 'measure' module from skimage

def visualize_predictions_as_contours(model, dataset, num_images=5, class_names=None):
    """
    Visualizes predictions of a segmentation model on the CPU, highlighting classes
    and optionally removing a specified class.

    Args:
        model: The trained segmentation model.
        dataset: The dataset to use for visualization.
        num_images: The number of images to visualize.
        class_names: A list of class names corresponding to the class indices.
                      If None, class indices will be used as labels.
    """

    model.eval()  # Set model to evaluation mode
    model.cpu()  # Ensure the model is on the CPU

    # Get random indices from the dataset
    indices = random.sample(range(len(dataset)), num_images)

    for idx in indices:
        image, mask = dataset[idx]  # Get image and mask
        image = image.cpu()  # Make sure the image is on the CPU

        with torch.no_grad():
            output = model(image.unsqueeze(0))  # Add batch dimension and make prediction
            prediction = torch.argmax(output, dim=1).squeeze()  # Get prediction and remove batch dimension

        # Plot original image, ground truth mask, and predicted mask
        plt.figure(figsize=(15, 5))

        plt.subplot(1, 3, 1)
        plt.imshow(image.squeeze(), cmap='gray')  # Remove channel dimension for display
        plt.title('Original Image')
        plt.axis('off')

        # Ground truth mask as contours
        plt.subplot(1, 3, 2)
        plt.imshow(image.squeeze(), cmap='gray')  # Background image
        # Create colormap for ground truth contours
        gt_colors = ['r', 'g', 'darkblue']
        for i, color in enumerate(gt_colors):
            contours = measure.find_contours(mask.cpu().numpy(), i + 0.5)  # Adjust level for each class
            for contour in contours:
                plt.plot(contour[:, 1], contour[:, 0], color, linewidth=2)
        plt.title('Ground Truth Mask (Contours)')
        plt.axis('off')

        # Predicted mask as contours
        plt.subplot(1, 3, 3)
        plt.imshow(image.squeeze(), cmap='gray')  # Background image
        # Create colormap for predicted contours
        pred_colors = ['magenta', 'yellow', 'lightblue']
        for i, color in enumerate(pred_colors):
            contours = measure.find_contours(prediction.cpu().numpy(), i + 0.5)  # Adjust level for each class
            for contour in contours:
                # Specify color and linestyle separately
                plt.plot(contour[:, 1], contour[:, 0], color=color, linestyle='--', linewidth=2)
        plt.title('Predicted Mask (Contours)')
        plt.axis('off')

        plt.show()

import matplotlib.pyplot as plt
import random
import torch
import numpy as np
from skimage import measure  # Import the 'measure' module from skimage

def visualize_predictions_as_contours(model, dataset, num_images=5, class_names=None):
    """
    Visualizes predictions of a segmentation model on the CPU, highlighting classes
    and optionally removing a specified class.

    Args:
        model: The trained segmentation model.
        dataset: The dataset to use for visualization.
        num_images: The number of images to visualize.
        class_names: A list of class names corresponding to the class indices.
                      If None, class indices will be used as labels.
    """

    model.eval()  # Set model to evaluation mode
    model.cpu()  # Ensure the model is on the CPU

    # Get random indices from the dataset
    indices = random.sample(range(len(dataset)), num_images)

    for idx in indices:
        image, mask = dataset[idx]  # Get image and mask
        image = image.cpu()  # Make sure the image is on the CPU

        with torch.no_grad():
            output = model(image.unsqueeze(0))  # Add batch dimension and make prediction
            prediction = torch.argmax(output, dim=1).squeeze()  # Get prediction and remove batch dimension

        # Plot original image, ground truth mask, and predicted mask
        plt.figure(figsize=(10, 5))  # Adjusted figure size

        # Display the original image in grayscale
        plt.imshow(image.squeeze(), cmap='gray')

        # Overlay ground truth contours
        gt_colors = ['r', 'g', 'darkblue']  # Colors for ground truth contours
        for i, color in enumerate(gt_colors):
            contours = measure.find_contours(mask.cpu().numpy(), i + 0.5)
            for contour in contours:
                plt.plot(contour[:, 1], contour[:, 0], color, linewidth=2, label=f'GT Class {i + 1}' if i == 0 else "")

        # Overlay predicted contours with dashed lines and different colors
        pred_colors = ['magenta', 'yellow', 'lightblue']  # Colors for predicted contours
        for i, color in enumerate(pred_colors):
            contours = measure.find_contours(prediction.cpu().numpy(), i + 0.5)
            for contour in contours:
                plt.plot(contour[:, 1], contour[:, 0], color=color, linestyle='--', linewidth=2, label=f'Pred Class {i + 1}' if i == 0 else "")

        # Customize the plot
        plt.title('Ultrasound Image with Overlaid Masks')
        plt.axis('off')
        plt.legend()  # Show legend to distinguish contours
        plt.show()

visualize_predictions_as_contours(model, test_dataset, num_images=5)  # Visualize 5 predictions

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Caminho para os frames
frames_path1 = "/content/drive/MyDrive/TOSHIBA_A4C_lcx_frames"

# Obter lista ordenada de imagens
frame_files = sorted([f for f in os.listdir(frames_path1) if f.endswith(".png")])

# Ler todos os frames em arrays (normalizando para [0,1])
frames = []
for file in frame_files:
    img = cv2.imread(os.path.join(frames_path1, file), cv2.IMREAD_GRAYSCALE)
    img_resized = cv2.resize(img, (256, 256))  # Se necessário
    img_norm = img_resized.astype(np.float32) / 255.0
    img_norm = np.expand_dims(img_norm, axis=(0, -1))  # (1, H, W, 1)
    frames.append(img_norm)

model_save_path = "/content/drive/MyDrive/final_model.pth"

import os
import numpy as np
import cv2
import torch
from torchvision import transforms
import matplotlib.pyplot as plt
from PIL import Image

!pip install segmentation-models-pytorch
from torch.utils.data import Subset, DataLoader
import segmentation_models_pytorch as smp # import the library as smp
import torch

model = smp.Unet(
    encoder_name="resnet34",
    encoder_weights="imagenet",
    in_channels=1,
    classes=4,
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

model.load_state_dict(torch.load("/content/drive/MyDrive/final_model.pth", map_location=device))
model.to(device)
model.eval()

# Caminho para os frames PNG
frames_path = "/content/drive/MyDrive/TOSHIBA_A4C_lcx_frames"
frame_files = sorted([f for f in os.listdir(frames_path) if f.endswith(".png")])

# Função para pré-processar um frame PNG
def preprocess_frame_png(path_to_png):
    # Lê com SimpleITK
    image = sitk.ReadImage(path_to_png)
    image_array = sitk.GetArrayFromImage(image)[0]  # Shape: (H, W)

    # Redimensiona para 320x320
    image_resized = cv2.resize(image_array, (320, 320), interpolation=cv2.INTER_LINEAR)

    # Normaliza imagem
    image_resized = image_resized.astype(np.float32) / 255.0

    # Converte para tensor [1, H, W]
    image_tensor = np.expand_dims(image_resized, axis=0)  # Shape: [1, H, W]
    return image_tensor


# Pasta de saída
save_path = "/content/drive/MyDrive/New_Masks"
os.makedirs(save_path, exist_ok=True)

# Loop de predição
for idx, frame_file in enumerate(frame_files):
    image_path = os.path.join(frames_path, frame_file)

    # Carrega e processa imagem
    image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    image_resized = cv2.resize(image, (320, 320))  # redimensiona
    image_norm = image_resized.astype(np.float32) / 255.0  # normalização simples

    # Converte para tensor [1, 1, H, W]
    input_tensor = torch.from_numpy(image_norm).unsqueeze(0).unsqueeze(0).to(device)

    with torch.no_grad():
        output = model(input_tensor)
        output = torch.sigmoid(output)

    # Gera máscara binária
    mask = output.squeeze().cpu().numpy()
    binary_mask = (mask > 0.5).astype(np.uint8) * 255

    # Salva a máscara
    out_path = os.path.join(save_path, f"mask_{idx:04d}.png")
    cv2.imwrite(out_path, binary_mask)

    # Exibe (opcional)
    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    plt.title("Frame")
    plt.imshow(image_resized, cmap='gray')
    plt.subplot(1, 2, 2)
    plt.title("Predicted Mask")
    plt.imshow(binary_mask, cmap='gray')
    plt.show()

!pip install SimpleITK
!pip install segmentation-models-pytorch

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import cv2
import torch
import matplotlib.pyplot as plt
import SimpleITK as sitk
import segmentation_models_pytorch as smp

# ✅ Define o modelo corretamente
model = smp.Unet(
    encoder_name="resnet34",
    encoder_weights="imagenet",
    in_channels=1,
    classes=4,
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.load_state_dict(torch.load("/content/drive/MyDrive/final_model.pth", map_location=device))
model = model.to(device)
model.eval()

# ✅ Caminho para os frames PNG
frames_path = "/content/drive/MyDrive/TOSHIBA_A4C_lcx_frames"
frame_files = sorted([f for f in os.listdir(frames_path) if f.endswith(".png")])

# ✅ Pasta de saída para salvar as máscaras
save_path = "/content/drive/MyDrive/New_Masks"
os.makedirs(save_path, exist_ok=True)

# ✅ Função de pré-processamento com SimpleITK
def preprocess_frame_png(path_to_png):
    # ✅ Lê com OpenCV em escala de cinza
    image = cv2.imread(path_to_png, cv2.IMREAD_GRAYSCALE)

    if image is None:
        raise ValueError(f"Imagem não carregada corretamente: {path_to_png}")

    # Redimensiona
    image_resized = cv2.resize(image, (320, 320), interpolation=cv2.INTER_LINEAR)

    # Normaliza
    image_resized = image_resized.astype(np.float32) / 255.0

    # Shape: [1, H, W]
    image_tensor = np.expand_dims(image_resized, axis=0)

    return image_tensor

# ✅ Loop para predição dos frames
for idx, frame_file in enumerate(frame_files):
    image_path = os.path.join(frames_path, frame_file)

    # Pré-processa com SimpleITK
    input_tensor = preprocess_frame_png(image_path)  # shape: [1, H, W]
    input_tensor = torch.from_numpy(input_tensor).unsqueeze(0).to(device)  # shape: [1, 1, H, W]

    with torch.no_grad():
        output = model(input_tensor)               # shape: [1, 4, H, W]
        output = torch.softmax(output, dim=1)      # aplica softmax nas classes
        pred_mask = torch.argmax(output, dim=1)    # shape: [1, H, W]

    # Converte para imagem numpy e escala para salvar como PNG
    mask_np = pred_mask.squeeze(0).cpu().numpy().astype(np.uint8)
    mask_img = (mask_np * (255 // 3)).astype(np.uint8)  # Escala para 0–255 para salvar

    # Salva a máscara
    out_path = os.path.join(save_path, f"mask_{idx:04d}.png")
    cv2.imwrite(out_path, mask_img)

    # Exibe imagem + máscara
    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    plt.title("Frame")
    plt.imshow(input_tensor.squeeze().cpu().numpy(), cmap='gray')
    plt.axis('off')
    plt.subplot(1, 2, 2)
    plt.title("Predicted Mask")
    plt.imshow(mask_img)
    plt.axis('off')
    plt.show()

# ✅ Loop para predição e visualização
for idx, frame_file in enumerate(frame_files):
    image_path = os.path.join(frames_path, frame_file)

    # Pré-processamento e predição
    input_tensor = preprocess_frame_png(image_path)
    input_tensor = torch.from_numpy(input_tensor).unsqueeze(0).to(device)

    with torch.no_grad():
        output = model(input_tensor)
        output = torch.softmax(output, dim=1)
        pred_mask = torch.argmax(output, dim=1)

    mask_np = pred_mask.squeeze().cpu().numpy().astype(np.uint8)

    # Visualização
    plt.figure(figsize=(10, 5))
    plt.imshow(input_tensor.squeeze().cpu().numpy(), cmap='gray')

    colors = ['magenta', 'yellow', 'cyan']
    class_names = ['Classe 1', 'Classe 2', 'Classe 3']

    for class_idx in range(1, 4):  # Classes 1, 2, 3
        # Inicializa a flag para controle de legenda
        contour_plotted = False

        # Detecta contornos para a classe atual
        contours = measure.find_contours(mask_np, class_idx - 0.5)

        for contour in contours:
            # Adiciona label apenas no primeiro contorno da classe
            label = class_names[class_idx-1] if not contour_plotted else None
            plt.plot(
                contour[:, 1],
                contour[:, 0],
                color=colors[class_idx-1],
                linestyle='--',
                linewidth=2,
                label=label
            )
            # Marca que a legenda já foi adicionada
            if not contour_plotted:
                contour_plotted = True

    plt.title(f"Frame {idx} com Segmentação")
    plt.axis('off')

    # Filtra entradas duplicadas na legenda
    handles, labels = plt.gca().get_legend_handles_labels()
    unique = dict(zip(labels, handles))  # Remove duplicatas
    plt.legend(unique.values(), unique.keys(), loc='upper right')

    plt.show()

    # Salva a máscara
    mask_img = (mask_np * (255 // 3)).astype(np.uint8)
    out_path = os.path.join(save_path, f"mask_{idx:04d}.png")
    cv2.imwrite(out_path, mask_img)

import cv2
import os

# ✅ Caminhos
frames_folder = "/content/drive/MyDrive/New_Masks"  # Pasta com as máscaras/frames
output_video_path = "/content/drive/MyDrive/segmentation_video.avi"  # Caminho do vídeo de saída

# ✅ Parâmetros do vídeo
frame_size = (320, 320)  # Tamanho igual ao dos frames (ajuste conforme seu caso)
fps = 60  # Taxa de frames por segundo

# ✅ Obter lista de frames ordenados
frame_files = sorted([f for f in os.listdir(frames_folder) if f.endswith(".png")])

# ✅ Criar objeto VideoWriter
fourcc = cv2.VideoWriter_fourcc(*'XVID')  # Codec para formato AVI
video_writer = cv2.VideoWriter(output_video_path, fourcc, fps, frame_size)

# ✅ Processar cada frame e adicionar ao vídeo
for frame_file in frame_files:
    frame_path = os.path.join(frames_folder, frame_file)
    frame = cv2.imread(frame_path)

    if frame is not None:
        video_writer.write(frame)
    else:
        print(f"Erro ao ler o frame: {frame_file}")

# ✅ Liberar recursos
video_writer.release()
print(f"Vídeo salvo em: {output_video_path}")

from IPython.display import HTML
from base64 import b64encode

# ✅ Exibir vídeo no notebook
video_path = open(output_video_path, "rb").read()
data_url = "data:video/avi;base64," + b64encode(video_path).decode()
HTML(f"""
<video width="400" controls>
    <source src="{data_url}" type="video/avi">
</video>
""")

import cv2
import os

frames_folder = "/content/drive/MyDrive/New_Masks"
output_video_path = "/content/drive/MyDrive/segmentation_video.avi"

# Verifique se há arquivos na pasta
frame_files = sorted([f for f in os.listdir(frames_folder) if f.endswith(".png")])
print(f"Número de frames encontrados: {len(frame_files)}")

# Teste a leitura do primeiro frame
if frame_files:
    test_frame_path = os.path.join(frames_folder, frame_files[0])
    test_frame = cv2.imread(test_frame_path)
    if test_frame is not None:
        print("Formato do primeiro frame:", test_frame.shape)
    else:
        print("Erro ao ler o primeiro frame!")

import cv2
import os

frames_folder = "/content/drive/MyDrive/New_Masks"
output_video_path = "/content/drive/MyDrive/segmentation_video.mp4"

# Verifique os frames
frame_files = sorted([f for f in os.listdir(frames_folder) if f.endswith(".png")])
if not frame_files:
    raise ValueError("Nenhum frame encontrado na pasta!")

# Obtenha o tamanho do primeiro frame
test_frame = cv2.imread(os.path.join(frames_folder, frame_files[0]))
if test_frame is None:
    raise ValueError("Não foi possível ler o primeiro frame!")
height, width, _ = test_frame.shape

# Configurações do vídeo
fps = 24
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
video_writer = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))

# Escreva os frames
for frame_file in frame_files:
    frame_path = os.path.join(frames_folder, frame_file)
    frame = cv2.imread(frame_path)
    if frame is not None:
        video_writer.write(frame)
    else:
        print(f"Frame inválido: {frame_file}")

video_writer.release()
print("Vídeo gerado com sucesso!")

from IPython.display import HTML
from base64 import b64encode

video_path = open(output_video_path, "rb").read()
data_url = "data:video/mp4;base64," + b64encode(video_path).decode()
HTML(f"""
<video width="400" controls>
    <source src="{data_url}" type="video/mp4">
</video>
""")

import os
import cv2
import imageio
import numpy as np
from PIL import Image

# ✅ Caminhos
frames_path = "/content/drive/MyDrive/TOSHIBA_A4C_lcx_frames"  # Frames originais
masks_path = "/content/drive/MyDrive/New_Masks"                # Máscaras
output_gif_path = "/content/drive/MyDrive/segmentation_animation.gif"

# ✅ Parâmetros
fps = 24  # Taxa de frames por segundo
alpha = 0.3  # Transparência da máscara (0 = transparente, 1 = opaco)

# ✅ Cores para cada classe (R, G, B)
class_colors = {
    1: (255, 0, 0),    # Vermelho para Classe 1
    2: (0, 255, 0),    # Verde para Classe 2
    3: (0, 0, 255)     # Azul para Classe 3
}

# ✅ Função para sobrepor máscaras
def overlay_mask(frame, mask_np, alpha):
    overlay = frame.copy()
    for class_idx, color in class_colors.items():
        class_mask = (mask_np == class_idx).astype(np.uint8)
        overlay[class_mask == 1] = (
            overlay[class_mask == 1] * (1 - alpha) + np.array(color) * alpha
        ).astype(np.uint8)
    return overlay

# ✅ Lista ordenada de frames e máscaras
frame_files = sorted([f for f in os.listdir(frames_path) if f.endswith(".png")])
mask_files = sorted([f for f in os.listdir(masks_path) if f.endswith(".png")])

# ✅ Processar cada frame
images_for_gif = []
for frame_file, mask_file in zip(frame_files, mask_files):
    # Carregar frame original
    frame = cv2.imread(os.path.join(frames_path, frame_file))
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)  # Converter para RGB

    # Carregar máscara
    mask = cv2.imread(os.path.join(masks_path, mask_file), cv2.IMREAD_GRAYSCALE)
    mask_resized = cv2.resize(mask, (frame.shape[1], frame.shape[0]))  # Garantir mesmo tamanho

    # Aplicar sobreposição
    overlayed = overlay_mask(frame, mask_resized, alpha)

    # Adicionar ao GIF
    images_for_gif.append(overlayed)

# ✅ Criar GIF
imageio.mimsave(
    output_gif_path,
    [Image.fromarray(img) for img in images_for_gif],
    duration=1000//fps,  # Duração por frame em ms
    loop=0               # Loop infinito
)

print(f"GIF salvo em: {output_gif_path}")

from IPython.display import Image
display(Image(filename=output_gif_path))

import os
import cv2
import imageio
import numpy as np
from PIL import Image

# ✅ Caminhos
frames_path = "/content/drive/MyDrive/TOSHIBA_A4C_lcx_frames"  # Pasta dos frames originais
masks_path = "/content/drive/MyDrive/New_Masks"                # Pasta das máscaras
output_gif_path = "/content/drive/MyDrive/segmentation_animation.gif"

# ✅ Parâmetros
fps = 24          # Taxa de frames por segundo
alpha = 0.5       # Transparência da máscara (0.5 = 50% de opacidade)

# ✅ Cores RGBA para cada classe (Vermelho, Verde, Azul)
class_colors = {
    1: (255, 255, 0, int(255 * alpha)),   # Classe 1: Amarelo
    2: (0, 0, 255, int(255 * alpha)),     # Classe 2: Azul
    3: (255, 0, 255, int(255 * alpha))    # Classe 3: Azul
}

# ✅ Função para sobrepor máscaras
def overlay_mask(base_frame, mask_np):
    # Converter a máscara para valores de classe originais (0, 1, 2, 3)
    mask_np = (mask_np // (255 // 3)).astype(np.uint8)  # Reverte a normalização

    # Criar uma imagem RGBA para a máscara
    overlay = np.zeros((*mask_np.shape, 4), dtype=np.uint8)

    for class_idx in [1, 2, 3]:
        overlay[mask_np == class_idx] = class_colors[class_idx]

    # Combinar com o frame original
    base_frame_rgba = cv2.cvtColor(base_frame, cv2.COLOR_RGB2RGBA)
    combined = cv2.addWeighted(base_frame_rgba, 1, overlay, 1, 0)

    return combined

# ✅ Listar arquivos
frame_files = sorted([f for f in os.listdir(frames_path) if f.endswith(".png")])
mask_files = sorted([f for f in os.listdir(masks_path) if f.endswith(".png")])

# ✅ Processar cada frame
images_for_gif = []
for frame_file, mask_file in zip(frame_files, mask_files):
    # Ler frame original
    frame = cv2.imread(os.path.join(frames_path, frame_file))
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)  # Converter para RGB

    # Ler máscara
    mask = cv2.imread(os.path.join(masks_path, mask_file), cv2.IMREAD_GRAYSCALE)
    mask = cv2.resize(mask, (frame.shape[1], frame.shape[0]))  # Ajustar tamanho

    # Aplicar sobreposição
    overlayed = overlay_mask(frame, mask)

    # Adicionar ao GIF
    images_for_gif.append(Image.fromarray(overlayed))

# ✅ Salvar GIF
imageio.mimsave(
    output_gif_path,
    images_for_gif,
    duration=1000//fps,  # Duração por frame em milissegundos
    loop=0               # Loop infinito
)

print(f"GIF salvo em: {output_gif_path}")

from IPython.display import Image
display(Image(filename=output_gif_path))

